CV_flag: False                                      # whether to use cross-validation
add_vocab_flag: False                               # whether to add supplementary vocab
LLRD_flag: False                                    # whether to use layer-wise lr decay
aug_flag: False                                     # whether to apply data augmentation
aug_special_flag: False                            # whether to augment copolymer SMILES
model_indicator: 'pretrain'                        # whether to use pretrained model
aug_indicator:                                     # number of augmentation per SMILES. If no limitation, assign the indicator with None (leave it blank).
lora_flag: True                                    # whether to use LoRA

vocab_sup_file: 'data/vocab/vocab_sup_PE_I.csv'     # supplementary vocab file path
train_file: 'data/neurips_augmented_train_Tc.csv'      # train file path
test_file: 'data/neurips_augmented_test_Tc.csv'        # test file path if cross-validation is not used
model_path: 'ckpt/pretrain.pt'                      # pretrain model path
save_path: 'ckpt/neurips.pt/Tc'                     # checkpoint path
# best_model_path: f"{save_path}/Rg1"          # best model save path
log_path: 'ckpt/neurips.pt/logs'                   # log path 

k: 2                                                # k-fold cross-validation
blocksize: 411                                      # max length of sequences after tokenization
batch_size: 4                                      # batch size
num_epochs: 10                                      # total number of epochs
warmup_ratio: 0.05                                  # warmup ratio
drop_rate: 0.1                                      # dropout
lr_rate: 0.00005                                    # initial lr for LLRD and pretrained model lr otherwise
lr_rate_reg: 0.0001                                 # regressor lr if LLRD is not used
weight_decay: 0.01
hidden_dropout_prob: 0.1                            # hidden layer dropout
attention_probs_dropout_prob: 0.1                   # attention dropout
tolerance: 2                                        # tolerance of no improvement in performance before early stop
num_workers: 0                                      # number of workers when loading data


